<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="elections.xsl" ?>

<!DOCTYPE DATA [
  <!ELEMENT DATA                     (RUN_DATE,RUN_EPOCH,RACE*)>
  <!ELEMENT RUN_DATE                 (CDATA)>
  <!ELEMENT RUN_EPOCH                (CDATA)>
  <!ELEMENT RACE                     (RACE_INFO,CANDIDATE_INFO)>
  <!ELEMENT RACE_INFO                (RACE_ID,JURISDICTION_ID,RACE_NAME1,RACE_NAME2,RACE_NAME3,RACE_NAME4,NUM_SEATS,PROMPT_LINES1,PROMPT_LINES2,ALLCAND_VOTES,PRECINCTS_TOTAL,PRECINCTS_REPORTING,PCT_PRECINCTS_REPORTING,UPDATED)>
  <!ELEMENT RACE_ID                  (ID)>
  <!ELEMENT JURISDICTION_ID          (CDATA)>
  <!ELEMENT RACE_NAME1               (CDATA)>
  <!ELEMENT RACE_NAME2               (CDATA)>
  <!ELEMENT RACE_NAME3               (CDATA)>
  <!ELEMENT RACE_NAME4               (CDATA)>
  <!ELEMENT NUM_SEATS                (CDATA)>
  <!ELEMENT PROMPT_LINES1            (CDATA)>
  <!ELEMENT PROMPT_LINES2            (CDATA)>
  <!ELEMENT ALLCAND_VOTES            (CDATA)>
  <!ELEMENT PRECINCTS_TOTAL          (CDATA)>
  <!ELEMENT PRECINCTS_REPORTING      (CDATA)>
  <!ELEMENT PCT_PRECINCTS_REPORTING  (CDATA)>
  <!ELEMENT UPDATED                  (CDATA)>
  <!ELEMENT CANDIDATE_INFO           (CANDIDATE*)>
  <!ELEMENT CANDIDATE                (CANDIDATE_ID,DISPLAY_ORDER,VISIBLE,FIRST_NAME,LAST_NAME,INCUMBENT,WINNER,PARTY_ID,PARTY_ABBR,PARTY_NAME1,PARTY_NAME2,VOTE_TOTAL,VOTE_TOTAL_COMMIFIED,PCT_TOTAL,PIC_ID)>
  <!ELEMENT CANDIDATE_ID             (CDATA)>
  <!ELEMENT DISPLAY_ORDER            (CDATA)>
  <!ELEMENT VISIBLE                  (CDATA)>
  <!ELEMENT FIRST_NAME               (CDATA)>
  <!ELEMENT LAST_NAME                (CDATA)>
  <!ELEMENT INCUMBENT                (CDATA)>
  <!ELEMENT WINNER                   (CDATA)>
  <!ELEMENT PARTY_ID                 (CDATA)>
  <!ELEMENT PARTY_ABBR               (CDATA)>
  <!ELEMENT PARTY_NAME1              (CDATA)>
  <!ELEMENT PARTY_NAME2              (CDATA)>
  <!ELEMENT VOTE_TOTAL               (CDATA)>
  <!ELEMENT VOTE_TOTAL_COMMIFIED     (CDATA)>
  <!ELEMENT PCT_TOTAL                (CDATA)>
  <!ELEMENT PIC_ID                   (CDATA)>
]>
<DATA>
   <RUN_DATE>Mon Feb  1 07:45:02 CST 2016</RUN_DATE>
   <RUN_EPOCH>1454334302</RUN_EPOCH>
   <RACE>
      <RACE_INFO>
         <RACE_ID>1</RACE_ID>
         <JURISDICTION_ID/>
         <RACE_NAME1>PRESIDENT</RACE_NAME1>
         <RACE_NAME2>Federal GOP</RACE_NAME2>
         <RACE_NAME3>President - Federal GOP</RACE_NAME3>
         <RACE_NAME4/>
         <NUM_SEATS>1</NUM_SEATS>
         <PROMPT_LINES1/>
         <PROMPT_LINES2/>
         <ALLCAND_VOTES>0</ALLCAND_VOTES>
         <PRECINCTS_TOTAL>0</PRECINCTS_TOTAL>
         <PRECINCTS_REPORTING>0</PRECINCTS_REPORTING>
         <PCT_PRECINCTS_REPORTING>0</PCT_PRECINCTS_REPORTING>
         <UPDATED/>
      </RACE_INFO>
      <CANDIDATE_INFO>
         <CANDIDATE>
            <CANDIDATE_ID>1</CANDIDATE_ID>
            <DISPLAY_ORDER>1</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Ben </FIRST_NAME>
            <LAST_NAME>Carson</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>2</CANDIDATE_ID>
            <DISPLAY_ORDER>2</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Carly</FIRST_NAME>
            <LAST_NAME>Fiorina</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>3</CANDIDATE_ID>
            <DISPLAY_ORDER>3</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Chris</FIRST_NAME>
            <LAST_NAME>Christie</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>4</CANDIDATE_ID>
            <DISPLAY_ORDER>4</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Donald J.</FIRST_NAME>
            <LAST_NAME>Trump</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>5</CANDIDATE_ID>
            <DISPLAY_ORDER>5</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Elizabeth</FIRST_NAME>
            <LAST_NAME>Gray</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>6</CANDIDATE_ID>
            <DISPLAY_ORDER>6</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Jeb</FIRST_NAME>
            <LAST_NAME>Bush</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>7</CANDIDATE_ID>
            <DISPLAY_ORDER>7</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>John R.</FIRST_NAME>
            <LAST_NAME>Kasich</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>8</CANDIDATE_ID>
            <DISPLAY_ORDER>8</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Lindsey</FIRST_NAME>
            <LAST_NAME>Graham</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>9</CANDIDATE_ID>
            <DISPLAY_ORDER>9</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Marco</FIRST_NAME>
            <LAST_NAME>Rubio</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>10</CANDIDATE_ID>
            <DISPLAY_ORDER>10</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Mike</FIRST_NAME>
            <LAST_NAME>Huckabee</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>11</CANDIDATE_ID>
            <DISPLAY_ORDER>11</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Rand</FIRST_NAME>
            <LAST_NAME>Paul</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>12</CANDIDATE_ID>
            <DISPLAY_ORDER>12</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Rick</FIRST_NAME>
            <LAST_NAME>Santorum</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>13</CANDIDATE_ID>
            <DISPLAY_ORDER>13</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Ted</FIRST_NAME>
            <LAST_NAME>Cruz</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
      </CANDIDATE_INFO>
   </RACE>
   <RACE>
      <RACE_INFO>
         <RACE_ID>2</RACE_ID>
         <JURISDICTION_ID/>
         <RACE_NAME1>U.S. REP. DISTRICT 15</RACE_NAME1>
         <RACE_NAME2>Statewide GOP</RACE_NAME2>
         <RACE_NAME3>U.S Representative District 15 - Statewide GOP</RACE_NAME3>
         <RACE_NAME4/>
         <NUM_SEATS>1</NUM_SEATS>
         <PROMPT_LINES1/>
         <PROMPT_LINES2/>
         <ALLCAND_VOTES>0</ALLCAND_VOTES>
         <PRECINCTS_TOTAL>0</PRECINCTS_TOTAL>
         <PRECINCTS_REPORTING>0</PRECINCTS_REPORTING>
         <PCT_PRECINCTS_REPORTING>0</PCT_PRECINCTS_REPORTING>
         <UPDATED/>
      </RACE_INFO>
      <CANDIDATE_INFO>
         <CANDIDATE>
            <CANDIDATE_ID>1</CANDIDATE_ID>
            <DISPLAY_ORDER>1</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Xavier</FIRST_NAME>
            <LAST_NAME>Salinas</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>2</CANDIDATE_ID>
            <DISPLAY_ORDER>2</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Ruben O.</FIRST_NAME>
            <LAST_NAME>Villarreal</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>3</CANDIDATE_ID>
            <DISPLAY_ORDER>3</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Tim</FIRST_NAME>
            <LAST_NAME>Westley</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
      </CANDIDATE_INFO>
   </RACE>
   <RACE>
      <RACE_INFO>
         <RACE_ID>3</RACE_ID>
         <JURISDICTION_ID/>
         <RACE_NAME1>U.S. REP. DISTRICT 28</RACE_NAME1>
         <RACE_NAME2>Statewide GOP</RACE_NAME2>
         <RACE_NAME3>U.S Representative District 28 - Statewide GOP</RACE_NAME3>
         <RACE_NAME4/>
         <NUM_SEATS>1</NUM_SEATS>
         <PROMPT_LINES1/>
         <PROMPT_LINES2/>
         <ALLCAND_VOTES>0</ALLCAND_VOTES>
         <PRECINCTS_TOTAL>0</PRECINCTS_TOTAL>
         <PRECINCTS_REPORTING>0</PRECINCTS_REPORTING>
         <PCT_PRECINCTS_REPORTING>0</PCT_PRECINCTS_REPORTING>
         <UPDATED/>
      </RACE_INFO>
      <CANDIDATE_INFO>
         <CANDIDATE>
            <CANDIDATE_ID>1</CANDIDATE_ID>
            <DISPLAY_ORDER>1</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Zeffen</FIRST_NAME>
            <LAST_NAME>Hardin</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
      </CANDIDATE_INFO>
   </RACE>
   <RACE>
      <RACE_INFO>
         <RACE_ID>4</RACE_ID>
         <JURISDICTION_ID/>
         <RACE_NAME1>U.S. REP. DISTRICT 34</RACE_NAME1>
         <RACE_NAME2>Statewide GOP</RACE_NAME2>
         <RACE_NAME3>U.S Representative District 34 - Statewide GOP</RACE_NAME3>
         <RACE_NAME4/>
         <NUM_SEATS>1</NUM_SEATS>
         <PROMPT_LINES1/>
         <PROMPT_LINES2/>
         <ALLCAND_VOTES>0</ALLCAND_VOTES>
         <PRECINCTS_TOTAL>0</PRECINCTS_TOTAL>
         <PRECINCTS_REPORTING>0</PRECINCTS_REPORTING>
         <PCT_PRECINCTS_REPORTING>0</PCT_PRECINCTS_REPORTING>
         <UPDATED/>
      </RACE_INFO>
      <CANDIDATE_INFO>
         <CANDIDATE>
            <CANDIDATE_ID>1</CANDIDATE_ID>
            <DISPLAY_ORDER>1</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Rey</FIRST_NAME>
            <LAST_NAME>Gonzalez, Jr.</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>2</CANDIDATE_ID>
            <DISPLAY_ORDER>2</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>William</FIRST_NAME>
            <LAST_NAME>Vaden</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
      </CANDIDATE_INFO>
   </RACE>
   <RACE>
      <RACE_INFO>
         <RACE_ID>5</RACE_ID>
         <JURISDICTION_ID/>
         <RACE_NAME1>RAILROAD COMMISSIONER</RACE_NAME1>
         <RACE_NAME2>Statewide GOP</RACE_NAME2>
         <RACE_NAME3>Railroad Commissioner - Statewide GOP</RACE_NAME3>
         <RACE_NAME4/>
         <NUM_SEATS>1</NUM_SEATS>
         <PROMPT_LINES1/>
         <PROMPT_LINES2/>
         <ALLCAND_VOTES>0</ALLCAND_VOTES>
         <PRECINCTS_TOTAL>0</PRECINCTS_TOTAL>
         <PRECINCTS_REPORTING>0</PRECINCTS_REPORTING>
         <PCT_PRECINCTS_REPORTING>0</PCT_PRECINCTS_REPORTING>
         <UPDATED/>
      </RACE_INFO>
      <CANDIDATE_INFO>
         <CANDIDATE>
            <CANDIDATE_ID>1</CANDIDATE_ID>
            <DISPLAY_ORDER>1</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Gary </FIRST_NAME>
            <LAST_NAME>Gates</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>2</CANDIDATE_ID>
            <DISPLAY_ORDER>2</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Ron</FIRST_NAME>
            <LAST_NAME>Hale</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>3</CANDIDATE_ID>
            <DISPLAY_ORDER>3</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Lance N.</FIRST_NAME>
            <LAST_NAME>Christian</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>4</CANDIDATE_ID>
            <DISPLAY_ORDER>4</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>John</FIRST_NAME>
            <LAST_NAME>Greytok</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>5</CANDIDATE_ID>
            <DISPLAY_ORDER>5</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Wayne</FIRST_NAME>
            <LAST_NAME>Christian</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>6</CANDIDATE_ID>
            <DISPLAY_ORDER>6</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Doug</FIRST_NAME>
            <LAST_NAME>Jeffrey</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>7</CANDIDATE_ID>
            <DISPLAY_ORDER>7</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Weston</FIRST_NAME>
            <LAST_NAME>Martinez</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
      </CANDIDATE_INFO>
   </RACE>
   <RACE>
      <RACE_INFO>
         <RACE_ID>6</RACE_ID>
         <JURISDICTION_ID/>
         <RACE_NAME1>JUSTICE, SUPREME COURT, PLACE 3</RACE_NAME1>
         <RACE_NAME2>Statewide GOP</RACE_NAME2>
         <RACE_NAME3>Justice, Supreme Court, PL 3 - Statewide GOP</RACE_NAME3>
         <RACE_NAME4/>
         <NUM_SEATS>1</NUM_SEATS>
         <PROMPT_LINES1/>
         <PROMPT_LINES2/>
         <ALLCAND_VOTES>0</ALLCAND_VOTES>
         <PRECINCTS_TOTAL>0</PRECINCTS_TOTAL>
         <PRECINCTS_REPORTING>0</PRECINCTS_REPORTING>
         <PCT_PRECINCTS_REPORTING>0</PCT_PRECINCTS_REPORTING>
         <UPDATED/>
      </RACE_INFO>
      <CANDIDATE_INFO>
         <CANDIDATE>
            <CANDIDATE_ID>1</CANDIDATE_ID>
            <DISPLAY_ORDER>1</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Michael</FIRST_NAME>
            <LAST_NAME>Massengale</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>2</CANDIDATE_ID>
            <DISPLAY_ORDER>2</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Debra</FIRST_NAME>
            <LAST_NAME>Lehrmann</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
      </CANDIDATE_INFO>
   </RACE>
   <RACE>
      <RACE_INFO>
         <RACE_ID>7</RACE_ID>
         <JURISDICTION_ID/>
         <RACE_NAME1>JUSTICE, SUPREME COURT, PLACE 5</RACE_NAME1>
         <RACE_NAME2>Statewide GOP</RACE_NAME2>
         <RACE_NAME3>Justice, Supreme Court, PL 5 - Statewide GOP</RACE_NAME3>
         <RACE_NAME4/>
         <NUM_SEATS>1</NUM_SEATS>
         <PROMPT_LINES1/>
         <PROMPT_LINES2/>
         <ALLCAND_VOTES>0</ALLCAND_VOTES>
         <PRECINCTS_TOTAL>0</PRECINCTS_TOTAL>
         <PRECINCTS_REPORTING>0</PRECINCTS_REPORTING>
         <PCT_PRECINCTS_REPORTING>0</PCT_PRECINCTS_REPORTING>
         <UPDATED/>
      </RACE_INFO>
      <CANDIDATE_INFO>
         <CANDIDATE>
            <CANDIDATE_ID>1</CANDIDATE_ID>
            <DISPLAY_ORDER>1</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Rick</FIRST_NAME>
            <LAST_NAME>Green</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>2</CANDIDATE_ID>
            <DISPLAY_ORDER>2</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Paul</FIRST_NAME>
            <LAST_NAME>Green</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
      </CANDIDATE_INFO>
   </RACE>
   <RACE>
      <RACE_INFO>
         <RACE_ID>8</RACE_ID>
         <JURISDICTION_ID/>
         <RACE_NAME1>JUSTICE, SUPREME COURT, PLACE 9</RACE_NAME1>
         <RACE_NAME2>Statewide GOP</RACE_NAME2>
         <RACE_NAME3>Justice, Supreme Court, PL 9 - Statewide GOP</RACE_NAME3>
         <RACE_NAME4/>
         <NUM_SEATS>1</NUM_SEATS>
         <PROMPT_LINES1/>
         <PROMPT_LINES2/>
         <ALLCAND_VOTES>0</ALLCAND_VOTES>
         <PRECINCTS_TOTAL>0</PRECINCTS_TOTAL>
         <PRECINCTS_REPORTING>0</PRECINCTS_REPORTING>
         <PCT_PRECINCTS_REPORTING>0</PCT_PRECINCTS_REPORTING>
         <UPDATED/>
      </RACE_INFO>
      <CANDIDATE_INFO>
         <CANDIDATE>
            <CANDIDATE_ID>1</CANDIDATE_ID>
            <DISPLAY_ORDER>1</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Eva</FIRST_NAME>
            <LAST_NAME>Guzman</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>2</CANDIDATE_ID>
            <DISPLAY_ORDER>2</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Joe</FIRST_NAME>
            <LAST_NAME>Pool</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
      </CANDIDATE_INFO>
   </RACE>
   <RACE>
      <RACE_INFO>
         <RACE_ID>9</RACE_ID>
         <JURISDICTION_ID/>
         <RACE_NAME1>JUDGE, CRIMINAL APPEALS COURT, PLACE 2 </RACE_NAME1>
         <RACE_NAME2>Statewide GOP</RACE_NAME2>
         <RACE_NAME3>Judge, Criminal Appeals Court, PL 2 - Statewide GOP</RACE_NAME3>
         <RACE_NAME4/>
         <NUM_SEATS>1</NUM_SEATS>
         <PROMPT_LINES1/>
         <PROMPT_LINES2/>
         <ALLCAND_VOTES>0</ALLCAND_VOTES>
         <PRECINCTS_TOTAL>0</PRECINCTS_TOTAL>
         <PRECINCTS_REPORTING>0</PRECINCTS_REPORTING>
         <PCT_PRECINCTS_REPORTING>0</PCT_PRECINCTS_REPORTING>
         <UPDATED/>
      </RACE_INFO>
      <CANDIDATE_INFO>
         <CANDIDATE>
            <CANDIDATE_ID>1</CANDIDATE_ID>
            <DISPLAY_ORDER>1</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Mary Lou</FIRST_NAME>
            <LAST_NAME>Keel</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>2</CANDIDATE_ID>
            <DISPLAY_ORDER>2</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Chris</FIRST_NAME>
            <LAST_NAME>Oldner</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
         <CANDIDATE>
            <CANDIDATE_ID>3</CANDIDATE_ID>
            <DISPLAY_ORDER>3</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>
            <FIRST_NAME>Ray</FIRST_NAME>
            <LAST_NAME>Wheless</LAST_NAME>
            <INCUMBENT>N</INCUMBENT>
            <WINNER/>
            <PARTY_ID/>
            <PARTY_ABBR/>
            <PARTY_NAME1/>
            <PARTY_NAME2/>
            <VOTE_TOTAL>0</VOTE_TOTAL>
            <VOTE_TOTAL_COMMIFIED>0</VOTE_TOTAL_COMMIFIED>
            <PCT_TOTAL>0</PCT_TOTAL>
            <PIC_ID/>
         </CANDIDATE>
      </CANDIDATE_INFO>
   </RACE>
   <RACE>
      <RACE_INFO>
         <RACE_ID>10</RACE_ID>
         <JURISDICTION_ID/>
         <RACE_NAME1>JUDGE, CRIMINAL APPEALS COURT, PLACE 5 </RACE_NAME1>
         <RACE_NAME2>Statewide GOP</RACE_NAME2>
         <RACE_NAME3>Judge, Criminal Appeals Court, PL 5 - Statewide GOP</RACE_NAME3>
         <RACE_NAME4/>
         <NUM_SEATS>1</NUM_SEATS>
         <PROMPT_LINES1/>
         <PROMPT_LINES2/>
         <ALLCAND_VOTES>0</ALLCAND_VOTES>
         <PRECINCTS_TOTAL>0</PRECINCTS_TOTAL>
         <PRECINCTS_REPORTING>0</PRECINCTS_REPORTING>
         <PCT_PRECINCTS_REPORTING>0</PCT_PRECINCTS_REPORTING>
         <UPDATED/>
      </RACE_INFO>
      <CANDIDATE_INFO>
         <CANDIDATE>
            <CANDIDATE_ID>1</CANDIDATE_ID>
            <DISPLAY_ORDER>1</DISPLAY_ORDER>
            <VISIBLE>Y</VISIBLE>